### ISSUE TITLE
Trigonometric                                                                                                                                    integrals

### ISSUE THREAD

**Issue by Anthony127** [mooculus/calculusE#2]
See [trigonometricIntegrals/digInTrigonometricIntegrals.tex](https://github.com/mooculus/calculusE/blob/3f12e3e08456c6c9f469b6900afca8fc483ac11e/trigonometricIntegrals/digInTrigonometricIntegrals.tex)

For the question that goes along with odd powers of cosine, the integral should be sec^90(x)*csc^59(x) not 
sec^90(x)*cot^59(x). However the hint denotes these as the correct form of secant and cosecant

**Comment by bartsnapp** [comment]
Actually the integral is correct - it's only the hint that has the typo:

The hint should read (and now does after update) "express sec and cot in terms of sin and cos."
