### ISSUE TITLE
Numbers  and  Taylor                                                                                                                                    series

### ISSUE THREAD

**Issue by Anthony127** [mooculus/calculusE#3]
Within the explanation for limit as x goes to zero of (sin(x)-x)/(x^3cos(x)) the x term in front of cos(x) is missing its cubed value.

See [numbersAndTaylorSeries/digInNumbersAndTaylorSeries.tex](https://github.com/mooculus/calculusE/blob/9652332db5b2cdbe6bb8f8b91c50f98f78ad6204/numbersAndTaylorSeries/digInNumbersAndTaylorSeries.tex)

**Comment by bartsnapp** [comment]
Ah thanks! I've fixed it and redeployed.
